FROM rust:1.90 as builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin retriever_api

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/retriever_api /app/fastcrawl-retriever
EXPOSE 8080
ENTRYPOINT ["/app/fastcrawl-retriever"]
